name: Terraform-lint

on:
  push:
    branches: [ feature/terraform-setup ]
  pull_request:
    branches: "*"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Use the latest version of the checkout action

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform
          terraform version

      - name: Install tflint
        run: |
          curl -Lo /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
          sudo unzip /tmp/tflint.zip -d /usr/local/bin/
          tflint --version

      - name: Validate Terraform Code
        run: |
          cd /home/runner/work/nestjs-framework-template/nestjs-framework-template/terraform
          ls -lrth  # Change to your Terraform code directory
          tflint
